import Head from 'next/head'
import HomePage from './homepage'
import { getNewProductList } from "./homepage/apiHomePage";
import axios from 'axios';

const Home = ({data}) => {
  return (
    <>
      <Head>
        <title>Vua Rau Sạch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Next.js has {data.length} ⭐️</p>
      <HomePage data={data}/>
    </>
  )
}


export async function getStaticProps() {
  const res = await fetch('https://api-dev.vuarausach.vn/products/customer?sort=approved_at&order=DESC')
  const {data} = await res.json()
  console.log("res", data)
  return {
    props: {
      data: data,
    },
  }
}



export default Home
