import type { ReactElement } from "react";
import Head from "next/head";
import {
  getNewProductList,
  getSellingProductList,
  getCategoryProduct,
  getPromotion,
  getOutstandingFarm,
} from "./homepage/apiHomePage";
import Layout from "src/layout/layout";
import type { NextPageWithLayout } from "pages/_app.page";
import SectionPromotion from "./homepage/parts/sectionPromotion";
import SectionOutstandingFarm from "./homepage/parts/sectionOutstandingFarm";
import SectionNewProducts from "./homepage/parts/sectionNewProducts";
import SectionSellingProducts from "./homepage/parts/sectionSellingProducts";
import SectionPreOrderProducts from "./homepage/parts/sectionPreOrderProducts";
import SectionFlashSellProducts from "./homepage/parts/sectionFlashSellProducts";
import SectionCategoryProduct from "./homepage/parts/sectionCategoryProduct";

const Home: NextPageWithLayout = ({
  dataPromotion,
  dataOutstandingFarm,
  dataNewProduct,
  dataSellingProduct,
  dataCategoryProduct,
}: any) => {
  return (
    <>
      <Head>
        <title>Vua Rau Sạch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionPromotion dataPromotion={dataPromotion} />
      <SectionOutstandingFarm dataOutstandingFarm={dataOutstandingFarm} />
      <SectionFlashSellProducts dataNewProduct={dataNewProduct} />
      <SectionNewProducts dataNewProduct={dataNewProduct} />
      <SectionSellingProducts dataSellingProduct={dataSellingProduct} />
      <SectionPreOrderProducts dataNewProduct={dataNewProduct} />
      <SectionCategoryProduct dataCategoryProduct={dataCategoryProduct} />
    </>
  );
};

export async function getStaticProps() {
  const dataNewProduct = await getNewProductList()
    .then((res) => {
      const data = res.data;
      return data;
    })
    .catch((error) => {
      const errors = error.response ? error.response.data : true;
      return errors;
    });
  const dataSellingProduct = await getSellingProductList()
    .then((res) => {
      const data = res.data;
      return data;
    })
    .catch((error) => {
      const errors = error.response ? error.response.data : true;
      return errors;
    });

  // category
  const dataCategoryProduct = await getCategoryProduct()
    .then((res) => {
      const data = res.data;
      return data;
    })
    .catch((error) => {
      const errors = error.response ? error.response.data : true;
      return errors;
    });

  // Promotion
  const dataPromotion = await getPromotion()
    .then((res) => {
      const data = res.data;
      return data;
    })
    .catch((error) => {
      const errors = error.response ? error.response.data : true;
      return errors;
    });

  // OutstandingFarm
  const dataOutstandingFarm = await getOutstandingFarm()
    .then((res) => {
      const data = res.data;
      return data;
    })
    .catch((error) => {
      const errors = error.response ? error.response.data : true;
      return errors;
    });
  return {
    props: {
      dataPromotion: dataPromotion,
      dataOutstandingFarm: dataOutstandingFarm,
      dataNewProduct: dataNewProduct,
      dataSellingProduct: dataSellingProduct,
      dataCategoryProduct: dataCategoryProduct,
    },
  };
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
