import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HomePage from './homepage'
import styles from '../styles/Home.module.scss'
import 'antd/dist/antd.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage/>
    </div>
  )
}

export default Home
