import Head from 'next/head'
import HomePage from './homepage'
import { getNewProductList } from "./homepage/apiHomePage";
import axios from 'axios';

const Home = ({stars}) => {
  return (
    <>
      <Head>
        <title>Vua Rau Sạch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Next.js has {stars} ⭐️</p>
      <HomePage/>
    </>
  )
}


export async function getStaticProps() {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const json = await res.json()

  console.log("res", json)
  return {
    props: {
      stars: json.stargazers_count,
    },
  }
}



export default Home
